CREATE DATABASE IF NOT EXISTS db;

USE db;

CREATE TABLE Users (
    UserID INT NOT NULL AUTO_INCREMENT,
    Fname VARCHAR(32) NOT NULL,
    Lname VARCHAR(32) NOT NULL,
    HPassword VARCHAR(32) NOT NULL,
    Email VARCHAR(32) NOT NULL UNIQUE,
    HomeAddress VARCHAR(32) NOT NULL,
    isAdmin BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY(UserID)
);

CREATE TABLE Products (
    ProdID INT NOT NULL AUTO_INCREMENT,
    Pname VARCHAR(32) NOT NULL,
    Price DECIMAL(9,2) NOT NULL,
    Pdesc TEXT NOT NULL,
    Picture VARCHAR(32) NOT NULL,
    Rating DECIMAL(2,1) DEFAULT 0,
    AmountInStock INT NOT NULL DEFAULT 0,
    IsAvailable BOOLEAN NOT NULL DEFAULT true,
    PRIMARY KEY(ProdID)
);

CREATE TABLE Cart (
    UserID INT NOT NULL,
    ProdID INT NOT NULL,
    AmountToBuy INT NOT NULL,
    PRIMARY KEY(UserID, ProdID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE, 
    FOREIGN KEY (ProdID) REFERENCES Products(ProdID) ON DELETE CASCADE
);

CREATE TABLE Orders (
    OrderID INT NOT NULL,
    ProdID INT NOT NULL,
    Pname VARCHAR(32) NOT NULL,
    UserID INT NOT NULL,
    UserName VARCHAR(32) NOT NULL,
    Address VARCHAR(32) NOT NULL,
    Price DECIMAL(9,2) NOT NULL,
    AmountToBuy INT(4) NOT NULL,
    OrderStatus ENUM('ToShip', 'Shipped', 'Completed') DEFAULT 'ToShip',
    PRIMARY KEY(OrderID, ProdID)
);

CREATE TABLE Reviews (
    ReviewID INT NOT NULL AUTO_INCREMENT,
    ProdID INT NOT NULL,
    UserName VARCHAR(32) NOT NULL,
    Rating INT(1) NOT NULL,
    Comment TEXT,
    PRIMARY KEY(ReviewID),
    FOREIGN KEY (ProdID) REFERENCES Products(ProdID) ON DELETE CASCADE
);